### ISSUE TITLE
observation类型转换错误

### ISSUE THREAD

**Issue by Code-Newborn** [indigoLovee/DDPG#1]
![image](https://user-images.githubusercontent.com/47051839/220357179-42f6681a-d171-467b-9013-0490a8c7f685.png)
此处运行不通过，报错：
f:\Github\DDPG\DDPG.py:51: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_new.cpp:233.)
  state = T.tensor(observation, dtype=T.float).to(device)
Traceback (most recent call last):
  File "f:\Github\DDPG\train.py", line 53, in <module>
    main()
  File "f:\Github\DDPG\train.py", line 31, in main
    action = agent.choose_action(observation, train=True)
  File "f:\Github\DDPG\DDPG.py", line 51, in choose_action
    state = T.tensor(observation, dtype=T.float).to(device)
ValueError: expected sequence of length 8 at dim 1 (got 0)

**Comment by Yzhtc** [comment]
同样的错误！

**Comment by zheng85** [comment]
请问这个错误怎么解决？我也遇到了，你们解决了吗？

**Comment by Code-Newborn** [comment]
忘记回帖了，已解决，改成如下所示：
![image](https://github.com/indigoLovee/DDPG/assets/47051839/87728ec6-e45c-414f-9a09-57acc642032d)
